# Введение в Pandas

[Pandas](https://pandas.pydata.org/) — это библиотека Python, предоставляющая широкие возможности для анализа данных. Данные, с которыми работают датасаентисты, часто хранятся в форме табличек — например, в форматах `.csv`, `.tsv` или `.xlsx`.

С помощью библиотеки Pandas такие табличные данные очень удобно загружать, обрабатывать и анализировать с помощью SQL-подобных запросов. А в связке с библиотеками [визуализации](https://towardsdatascience.com/4-key-players-in-python-data-visualization-ecosystem-matplotlib-seaborn-altair-and-plotly-23ae37a68227/) [`Matplotlib`](https://matplotlib.org/)/[`Seaborn`](https://seaborn.pydata.org/)/[`Plotly`](https://plotly.com/) и библиотеками математической обработки данных[`Numpy`](https://numpy.org/)/[`SciPy`](https://scipy.org/) библиотека Pandas предоставляет широкие возможности визуального анализа табличных данных.

Основной структурой данных в Pandas является класс DataFrame.<br>
__DataFrame__ – это двухмерная структура данных, представляющая собой таблицу, каждый столбец которой содержит данные одного типа. Можно представлять её как словарь объектов типа колонки с индексами. Структура DataFrame отлично подходит для представления реальных данных: строки соответствуют признаковым описаниям отдельных объектов, а столбцы соответствуют признакам.

Также Pandas позволяет более оптимально работать с одномерными массивами при помощи класса  Series.<br>
__Series__ - представляет собой одномерный индексированный массив данных некоторого фиксированного типа.

In [1]:
# импортируем Pandas и Numpy
import pandas as pd
import numpy as np

# Набор данных

## Загрузка набора данных

**Оценка стоимости  и типа трансмиссии по данным продаж автомобилей на вторичном рынке Молдавии**

Набор данных представляет собой статистику параметров автомобилей на вторичном рынке в Молдавии.

* Набор включает ряд категориальных и численных значений, составляющих одну запись (строку).
* Число записей можно найти как число строк.
* Каждый столбец в записи — это отдельный параметр.
* Среди указанных параметров приведены целевой для задачи предсказания (регрессии) - цена автомобиля.
* Также среди параметров есть целевой для задачи классификации - тип трансмиссии.
* Последняя задача может быть рассмотрена, например, как пример задачи на заполнение пропусков (если продавец не указал соответствующий параметр).

Считываем файл в `DataFrame` - для этого использууем  метод `.read_csv(...)`

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/MVRonkin/BasicDataAnalysisCourse/refs/heads/main/Workshops/cars.csv')

посмотрим на содержание таблицы

## Визуализация данных

In [ ]:
df

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,True,7750.0
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,False,8550.0
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,False,2200.0
3,Renault,Laguna,2012,Universal,110000.0,1500.0,Diesel,False,6550.0
4,Opel,Astra,2006,Universal,200000.0,1600.0,Metan/Propan,False,4100.0
...,...,...,...,...,...,...,...,...,...
41002,Dacia,Logan Mcv,2015,Universal,89000.0,1500.0,Diesel,False,7000.0
41003,Renault,Modus,2009,Hatchback,225.0,1500.0,Diesel,False,4500.0
41004,Mercedes,E Class,2016,Sedan,50000.0,1950.0,Diesel,True,29500.0
41005,Mazda,6,2006,Combi,370000.0,2000.0,Diesel,False,4000.0
41006,Renault,Grand Scenic,2006,Minivan,300000.0,1500.0,Diesel,False,4000.0

Также для вывода можно использовать специальные методы:
* `head` - первые строки таблицы
* `sample` - случайные строки таблицы
* `tail` - последние строки таблицы

посмотрим на 3 первых строки

In [3]:
df.head(3)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,True,7750.0
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,False,8550.0
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,False,2200.0

Проверим размер таблицы

In [4]:
print(df.shape)

(41007, 9)

Теперь посмотрим на названия колонок

In [5]:
print(df.columns)

Index(['Make', 'Model', 'Year', 'Style', 'Distance', 'Engine_capacity(cm3)',
       'Fuel_type', 'AutoTransmission', 'Price(euro)'],
      dtype='object')

`DataFrame` можно отсортировать по значению какого-нибудь из признаков. Однако не рекоментся сохранять такой `DataFrame`.

Метод `.sort_values(by)`

In [ ]:
df.sort_values(by = 'Price(euro)').tail(5)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
16841,Volkswagen,Caddy,2015,Combi,158260.0,1395.0,Metan/Propan,False,200000.0
15016,Toyota,Land Cruiser Prado,2012,SUV,10005.0,3000.0,Diesel,True,200000.0
32170,Mercedes,G Class,2020,SUV,3000.0,3982.0,Petrol,True,215000.0
20055,KIA,Sportage,2018,Crossover,46000.0,1600.0,Petrol,True,490000.0
37125,Brilliance,BS3,2009,Sedan,57000.0,1598.0,Petrol,False,10000000.0


Метод `.sort_values(by, ascending= False)`

In [ ]:
df.sort_values(by = 'Year', ascending= False).head(5)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
26337,KIA,Optima,2021,Sedan,2000.0,1598.0,Petrol,True,23599.0
7739,Dacia,Duster,2021,Crossover,0.0,1500.0,Diesel,False,15900.0
16470,Volvo,NaN,2021,Sedan,0.0,2000.0,Diesel,True,53700.0
23063,Mercedes,GLA,2021,Crossover,7500.0,1998.0,Petrol,True,17000.0
10515,Dacia,Duster,2021,Crossover,0.0,1500.0,Diesel,False,17900.0

## Вывод информации о DataFrame

Выведем информацию о данных при помощи метода `.info() `

In [ ]:
# Основные свойства DataFrame

# print("Тип объекта:", type(df))
# print("Размер DataFrame (строки, столбцы):", df.shape)
# print("Число измерений:", df.ndim)
# print("Общее число элементов:", df.size)

# print("\nНазвания столбцов:")
# print(df.columns.tolist())

print("\nИндекс:")
print(df.index)

print("\nТипы данных:")
print(df.dtypes)

print("\nИспользование памяти:")
print(df.memory_usage(deep=True))
print(f"Всего: {df.memory_usage(deep=True).sum() / 1024:.1f} КБ")

Индекс:
RangeIndex(start=0, stop=41007, step=1)

Типы данных:
Make                     object
Model                    object
Year                      int64
Style                    object
Distance                float64
Engine_capacity(cm3)    float64
Fuel_type                object
AutoTransmission           bool
Price(euro)             float64
dtype: object

Использование памяти:
Index                       132
Make                    2579657
Model                   2578964
Year                     328056
Style                   2620332
Distance                 328056
Engine_capacity(cm3)     328056
Fuel_type               2608810
AutoTransmission          41007
Price(euro)              328056
dtype: int64
Всего: 11465.9 КБ

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41007 entries, 0 to 41006
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Make                  40802 non-null  object
 1   Model                 40802 non-null  object
 2   Year                  41007 non-null  int64
 3   Style                 41007 non-null  object
 4   Distance              41007 non-null  float64
 5   Engine_capacity(cm3)  40802 non-null  float64
 6   Fuel_type             40802 non-null  object
 7   AutoTransmission      41007 non-null  bool
 8   Price(euro)           41007 non-null  float64
dtypes: bool(1), float64(3), int64(1), object(4)
memory usage: 2.5+ MB

Из результата видно что `bool`, `int64`, `float64` и `object` — это типы признаков. Видим, что 1 признак — логический (`bool`), 4 признака имеют тип `object` и 3 признаков — числовые c плавоющей точкой (`float`) и 1 целочисленный признак (`int`). Также с помощью метода `info` удобно быстро посмотреть на пропуски в данных, в нашем случае пропуски имеются в столбцах 'Make', 'Model','Engine_capacity(cm3)', 'Fuel_type' - в этих стоблцах на 5 значений меньше, чем в остальных

Проверим где пропуски

In [ ]:
missing_values_count = df.isna().sum()
print(missing_values_count)

Make                    205
Model                   205
Year                      0
Style                     0
Distance                  0
Engine_capacity(cm3)    205
Fuel_type               205
AutoTransmission          0
Price(euro)               0
dtype: int64


Дополнительно найдем дбликаты данных (методы `.duplicated()` и `.sum()`)

In [ ]:
df.duplicated().sum()

np.int64(3623)

Для категориальных (тип `object`) и булевых (тип `bool`) признаков можно воспользоваться методом `value_counts`. Посмотрим на распределение данных переменной — `Fuel_type`:

In [ ]:
df['Fuel_type'].value_counts()

Fuel_type
Diesel            18810
Petrol            14475
Metan/Propan       4476
Hybrid             2179
Plug-in Hybrid      524
Electric            338
Name: count, dtype: int64

<!-- ## Упражнения -->
<!-- 1. Посчитайте число уникальных значений в категориальных колонках (`nunique()`) -->
<!-- 2. Посчитайте частоту встречи уникальных значений в колонке `Make`. Какой вывод можно сделать из этого если наша цель предсказывать цену популярных автомобилей?
3.  Проверьте статистику по годам в базе данных. Какой вывод можно сделать по наиболее старым автомобилям? -->

# Индексация

## Индекскация по колонкам

`DataFrame` можно индексировать по-разному. В связи с этим рассмотрим различные способы индексации и извлечения нужных нам данных из датафрейма на примере простых вопросов.

Для извлечения отдельного столбца можно использовать конструкцию вида `DataFrame['Name']`

In [ ]:
df[['AutoTransmission','Price(euro)']].head(3)

   AutoTransmission  Price(euro)
0              True       7750.0
1             False       8550.0
2             False       2200.0

Тоже самое, но `Series`

In [ ]:
df['AutoTransmission'].head(3)

0     True
1    False
2    False
Name: AutoTransmission, dtype: bool

Выбирем все колонки кроме цены - как входные данные и создадим целевой датафрейм с колонкой цена.

In [ ]:
df_X = df[[x for x in df.columns if x not in ['Price(euro)']]].copy()
df_y = df[['Price(euro)']].copy()

In [ ]:
df_X

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,True
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,False
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,False
3,Renault,Laguna,2012,Universal,110000.0,1500.0,Diesel,False
4,Opel,Astra,2006,Universal,200000.0,1600.0,Metan/Propan,False
...,...,...,...,...,...,...,...,...
41002,Dacia,Logan Mcv,2015,Universal,89000.0,1500.0,Diesel,False
41003,Renault,Modus,2009,Hatchback,225.0,1500.0,Diesel,False
41004,Mercedes,E Class,2016,Sedan,50000.0,1950.0,Diesel,True
41005,Mazda,6,2006,Combi,370000.0,2000.0,Diesel,False
41006,Renault,Grand Scenic,2006,Minivan,300000.0,1500.0,Diesel,False

## Индексация по слайсам и индексам

Датафреймы можно индексировать как по названию столбца или строки, так и по порядковому номеру. Для индексации по названию используется метод `loc`, по номеру — `iloc`.

например `.loc[строки, столбцы]`

Отметим, что функции `loc` и `iloc` представляют собой прямое обращение  к ячейки памятми `DataFrame` в отличии от обращения впрямую.

In [ ]:
df.loc[:,'AutoTransmission']

0         True
1        False
2        False
3        False
4        False
         ...
41002    False
41003    False
41004     True
41005    False
41006    False
Name: AutoTransmission, Length: 41007, dtype: bool

конкретное значение

In [ ]:
df.loc[1437,'AutoTransmission']

np.True_

слайс

In [ ]:
df.loc[0:5,['AutoTransmission']]

   AutoTransmission
0              True
1             False
2             False
3             False
4             False
5             False

In [ ]:
df.loc[0:10,['AutoTransmission','Year']].head(3)

   AutoTransmission  Year
0              True  2011
1             False  2014
2             False  1998

In [ ]:
df.loc[:,'Make':'Style'].head(3)

         Make         Model  Year      Style
0      Toyota         Prius  2011  Hatchback
1     Renault  Grand Scenic  2014  Universal
2  Volkswagen          Golf  1998  Hatchback

строка

In [ ]:
df.loc[69,:]

Make                        Honda
Model                        CR-V
Year                         2002
Style                   Universal
Distance                 275100.0
Engine_capacity(cm3)       2000.0
Fuel_type                  Petrol
AutoTransmission            False
Price(euro)                5900.0
Name: 69, dtype: object

In [ ]:
df.loc[[69],:]

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
69,Honda,CR-V,2002,Universal,275100.0,2000.0,Petrol,False,5900.0

слайс строк

In [ ]:
df.loc[322:1437,:].head(3)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
322,Volkswagen,Polo,2007,Hatchback,240000.0,1400.0,Diesel,False,3750.0
323,Audi,A6,2018,Sedan,0.0,1800.0,Petrol,True,25999.0
324,Hyundai,Santa FE,2015,Crossover,161000.0,2000.0,Diesel,True,18000.0

In [ ]:
df.loc[227:229,'Make':'Fuel_type']

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type
227,Audi,Q5,2013,SUV,143000.0,2000.0,Petrol
228,Volkswagen,Caddy,2013,Universal,174000.0,2000.0,Diesel
229,Toyota,Prius,2011,Hatchback,121000.0,1800.0,Hybrid

`iloc` индексация

In [ ]:
df.iloc[0:5, 0:3]

         Make         Model  Year
0      Toyota         Prius  2011
1     Renault  Grand Scenic  2014
2  Volkswagen          Golf  1998
3     Renault        Laguna  2012
4        Opel         Astra  2006

In [ ]:
df.iloc[0:1]

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,True,7750.0

In [ ]:
df.iloc[-1:]

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
41006,Renault,Grand Scenic,2006,Minivan,300000.0,1500.0,Diesel,False,4000.0

## Логическое Индексирование

Очень удобной является логическая индексация `DataFrame` по одному столбцу. Выглядит она следующим образом: `df[P(df['Name'])]`, где `P` — это некоторое логическое условие, проверяемое для каждого элемента столбца `Name`. Итогом такой индексации является `DataFrame`, состоящий только из строк, удовлетворяющих условию `P` по столбцу `Name`.

In [ ]:
df[df['AutoTransmission']==False].head(3)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,False,8550.0
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,False,2200.0
3,Renault,Laguna,2012,Universal,110000.0,1500.0,Diesel,False,6550.0

Найдем автомобили до 1970 года

In [ ]:
df[df['Year']<1970].head(3)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
3640,Moskvich / Izh,Altele,1964,Sedan,65000.0,100.0,Petrol,False,2500.0
4088,Zaz,Altele,1966,Sedan,37000.0,900.0,Petrol,False,2800.0
4187,Moskvich / Izh,Altele,1964,Sedan,45000.0,1200.0,Petrol,False,2300.0

Найдем пример очевидно протеворечивых данных

для этого можно использовать комбинации условий. Комбинации условий `&` - "и", `|` - "или", `~` - "не"

In [ ]:
df[(df['Year']<1950)&(df['AutoTransmission']==True)].head(3)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
13394,Audi,100,1900,Sedan,0.0,1000.0,Petrol,True,1500.0
18214,Volvo,S80,1900,Coupe,1556666.0,1212.0,Petrol,True,10000.0
18380,Peugeot,206,1900,Sedan,1877.0,1400.0,Petrol,True,3000.0

Воспользуемся этим для ответа на вопрос: каково среднее значение цены на `Toyota Land Cruiser Prado` с автоматической коробкой передч `2012` года

In [ ]:
df_selet = df[
    (df['AutoTransmission']==True)&\
    (df['Make']=='Toyota')&\
    (df['Year']==2012)&\
    (df['Model']=='Land Cruiser Prado')
]
df_selet['Price(euro)'].mean()

np.float64(38354.27272727273)

через SQL  запрос

In [ ]:
df_select = df.query(
    "AutoTransmission == True and "
    "Make == 'Toyota' and "
    "Year == 2012 and "
    "Model == 'Land Cruiser Prado'"
)

df_select['Price(euro)'].mean()

np.float64(38354.27272727273)

## Упражнения
<!-- 1. Выбирите `DataFrame` без пустых записей (`df.isna()` - для проверки пустых значений.)
   > *Подсказка*. Можно использовать метод `.dropna()` вместо условия. -->
1. Отфильтруйте часть `DataFrame` от записей очевидно противоречащами здравому смыслу, например:
    <!-- * пробег в год: пробег автомобиля (`Distance`) меньше `1000 км` и год автомобиля меньше `2021`.
      > *Подсказка*. Для этого можно использовать или комбинацию фильтров
      > или воспользоваться переменной год автомобиля
      > ```python
      > df['Year'].max()+1 - df['Year']`.
      > ``` -->
    * объем двиготеля (`Engine_capacity(cm3)`) меньше `200 см3` или больше `5000 см3`
    * цена (`Price(euro)`) - выбирите сами
      > *Подсказка*. Можно использовать `df_selet[['Price(euro)']].describe()`
    * год авто с автоматической трансмиссией (аналогично примеру выше)
    * свой вариант?
<!-- 4. Выбирите часть `DataFrame` без пропусков и часть с пропусками -->
2. Выбирите часть `DataFrame` только с численными колонками      
3. Сделайте функцию которая по заданным параметрам `Make`, `Model`и `Year` выводит датафрейм с типами `AutoTransmission`

<details>
    
  <summary><i>Подсказка</i> к 1 задаче</summary><br>
    
```python
    df_selet = df.copy()
    
    df_selet =  df_selet[
        (df_selet['Engine_capacity(cm3)']>200)&\
        (df_selet['Engine_capacity(cm3)']<5000)
    ]
    
    df_selet =  df_selet[
        (df_selet['Price(euro)']<=0.9*df_selet['Price(euro)'].max())
    ]
    
    df_selet =  df_selet[
        (df_selet['Price(euro)']>df_selet['Price(euro)'].min())
    ]
    
    df_selet =  df_selet[
        ~((df_selet['Year']<1970)&\
          (df_selet['AutoTransmission']==True))
    ]
    
    df = df_selet.copy()
```

</detailed>

In [ ]:
df_selet = df.copy()

df_selet =  df_selet[(df_selet['Engine_capacity(cm3)']>200)&\
        (df_selet['Engine_capacity(cm3)']<5000) ]


df_selet =  df_selet[
        ~((df_selet['Year']<1970)&\
          (df_selet['AutoTransmission']==True))
    ]



df_drop = df.copy()
df_drop =df_drop[~(df_drop['Engine_capacity(cm3)']>200)&\
        (df_drop['Engine_capacity(cm3)']<5000) ]

In [ ]:
df_selet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35404 entries, 0 to 36568
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Make                  35404 non-null  object
 1   Model                 35404 non-null  object
 2   Year                  35404 non-null  int64
 3   Style                 35404 non-null  object
 4   Distance              35404 non-null  float64
 5   Engine_capacity(cm3)  35404 non-null  float64
 6   Fuel_type             35404 non-null  object
 7   AutoTransmission      35404 non-null  bool
 8   Price(euro)           35404 non-null  float64
dtypes: bool(1), float64(3), int64(1), object(4)
memory usage: 2.5+ MB

# Предобработка DataFrame

## Простые операции

### Удаление дубликатов

Методы `.drop_duplicates()` и `.reset_index()`

In [ ]:
df = df.drop_duplicates()

df = df.reset_index(drop=True)

df.head(3)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,True,7750.0
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,False,8550.0
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,False,2200.0

Также удалим пропуски. Но отметим, что удаление пропусков в реальных задачах требует обоснования. Иногда пропуски лучше заполнить, чем удалить

In [ ]:
df = df.dropna()
df = df.reset_index(drop=True)

__Предлагается__ в качестве упражнени на дом найти пропуски в данных и по возможности заполнить их ближайшими по смыслу условиями.

### Создание своих столбцев

Зная суть или модель данных, мы можем предположить, чего нам не хватает - то есть попробовать добавить новый признак в данные. Такую операцию можно провести по-разному. В данном случае мы сделаем это исходя из логики. Введем признак пробег в год (`km_year`).

In [6]:
df['Age'] = df.Year.max()+1 - df.Year

df['km_year'] = df.Distance/df.Age

Применение функции к каждой ячейке `map`

In [7]:
d = {True : 'Automatic', False : 'Manual'}
df['Transmission'] = df['AutoTransmission'].map(d)
df.head()

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro),Age,km_year,Transmission
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,True,7750.0,11,17727.272727,Automatic
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,False,8550.0,8,16875.000000,Manual
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,False,2200.0,24,0.041667,Manual
3,Renault,Laguna,2012,Universal,110000.0,1500.0,Diesel,False,6550.0,10,11000.000000,Manual
4,Opel,Astra,2006,Universal,200000.0,1600.0,Metan/Propan,False,4100.0,16,12500.000000,Manual

Также давайте считать, что условный пробег в год может быть небольшим (например до 10 000 в год), средним (от 10 000 до 30 000) и большим (все что свыше). Создадим функцию которая бы реализовала эту функцию.

In [8]:
def km_year_category(km_year):
    if km_year <= 10_000:
        return 'Small'
    elif km_year > 10_000 and km_year <= 30_000:
        return 'Medium'
    else:
        return 'Large'

Создадим новый столбец и заполним его при помощи функции `apply`, которая применяет к заданному столбцу функцию, передаваяему в качестве аргумента.

In [9]:
df["km_year_cat"] = df["km_year"].apply(km_year_category)
df.head(3)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro),Age,km_year,Transmission,km_year_cat
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,True,7750.0,11,17727.272727,Automatic,Medium
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,False,8550.0,8,16875.000000,Manual,Medium
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,False,2200.0,24,0.041667,Manual,Small

### Удаление лишних столбцев

In [10]:
df = df.drop(columns = ['Age','AutoTransmission'])
df.head(3)

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,Price(euro),km_year,Transmission,km_year_cat
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,7750.0,17727.272727,Automatic,Medium
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,8550.0,16875.000000,Manual,Medium
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,2200.0,0.041667,Manual,Small

### Удаление при помощи фильтра по индексам

In [ ]:
# здравый смысл
question_dist = df[(df.Year <2021) & (df.Distance < 1100)]
df = df.drop(question_dist.index)

# редкие значения
question_dist = df[(df.Distance > 1e6)]
df = df.drop(question_dist.index)

# здравый смысл
question_engine = df[df["Engine_capacity(cm3)"] < 200]
df = df.drop(question_engine.index)

# здравый смысл
question_engine = df[df["Engine_capacity(cm3)"] > 5000]
df = df.drop(question_engine.index)

# здравый смысл
question_price = df[(df["Price(euro)"] < 101)]
df = df.drop(question_price.index)

# здравый смысл
question_price = df[df["Price(euro)"] > 5e5]
df = df.drop(question_price.index)

# редкие значения
question_year = df[df.Year < 1951]
df = df.drop(question_year.index)

df = df.reset_index(drop=True)
df.tail()

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,AutoTransmission,Price(euro)
32062,Volkswagen,Passat,2016,Sedan,88000.0,1800.0,Petrol,True,11500.0
32063,Land Rover,Freelander,2002,Crossover,225000.0,1800.0,Metan/Propan,False,4400.0
32064,Dacia,Logan Mcv,2015,Universal,89000.0,1500.0,Diesel,False,7000.0
32065,Mazda,6,2006,Combi,370000.0,2000.0,Diesel,False,4000.0
32066,Renault,Grand Scenic,2006,Minivan,300000.0,1500.0,Diesel,False,4000.0

Желательно при фильтрации проверять сколько осталось

In [ ]:
df.shape

(32067, 9)

### Переименование столбцов

In [ ]:
df = df.rename(columns={'Engine_capacity(cm3)':'Engine','Price(euro)':'Price'})

### Поиск редких значений в категориальных столбцах

Оказалось, что часть признаков в категориальных столбцах имеют слишком много записей. Вероятно, редкие из них можно исключить без потери точности. Мы сделаем эту операцию объявив такие записи одним значениям - `Rare`.

Выбирем значения колонки `Make`, где частота повторения данных менее `1%`

In [13]:
counts = df['Make'].value_counts()
counts

Make
Volkswagen      4286
Mercedes        3789
Toyota          3752
BMW             3205
Renault         2970
                ...
Lamborghini        1
McLaren            1
Saturn             1
Aston Martin       1
Xpeng              1
Name: count, Length: 87, dtype: int64

In [12]:
counts = df.Make.value_counts()
freqs = counts/sum(counts)
print(freqs)

Make
Volkswagen      0.105044
Mercedes        0.092863
Toyota          0.091956
BMW             0.078550
Renault         0.072791
                  ...
Lamborghini     0.000025
McLaren         0.000025
Saturn          0.000025
Aston Martin    0.000025
Xpeng           0.000025
Name: count, Length: 87, dtype: float64

Будем считать автомобили редкими, если их менее 1%.

In [ ]:
rare=counts[freqs<=0.01]
rare

Make
Citroen         297
Land Rover      286
Seat            238
Porsche         188
Fiat            187
               ...
Abarth            1
McLaren           1
Tata              1
Saturn            1
Aston Martin      1
Name: count, Length: 61, dtype: int64

Теперь в колонке `Make` проведем замену всех значений `Rare`

In [ ]:
df['Make'] = df['Make'].replace(rare.index.values, 'Rare')
df.Make.value_counts()

Make
Volkswagen    3403
Toyota        3024
Mercedes      3002
Rare          2595
BMW           2561
Renault       2334
Opel          1837
Skoda         1702
Audi          1536
Dacia         1349
Ford          1331
Nissan        1246
Hyundai       1197
Honda          893
KIA            650
Mitsubishi     610
Lexus          585
Volvo          574
Vaz            491
Mazda          441
Peugeot        384
Chevrolet      322
Name: count, dtype: int64

Обработанные `DataFrames` рекомендуется сохрнаять

In [ ]:
df['Age'] = df.Year.max()+1 - df.Year

df['km_year'] = df.Distance/df.Age

In [14]:
df.to_csv('cars_processed.csv',index=False)

## Упражнения
1. Для новых столбцев `km_year_cat` и  `km_year` проведите анализ значений на здравый смысл, например уберите строки где пробег более `100_000` в год.
2. Сделайте функцию которая для заданных параметров `Make`, `Model`и `Year` предлагает самый частый тип `Style`. Рассмотрите возможность удалания данного столбца на основе анализа при помощи данной функции.
3. Сделайте функцию, которая для заданных параметров `Make`, `Model`и `Year` предлагает самый частый тип `Fuel_type`.
4. Проведите устранение редких значений колонки `Models`
<!-- 5. Проведите анализ пропущенных значений, рассмотрите возможность их заполнения аналогичными (максимально близкими по смыслу) значениями. Пропущенные значения можно найти например при помощи функции `df[df.Fuel_type.isna()]`. Если пропущенное значение не удется обоснованно заполнить предлагается его удалить
```python
df = df.drop(index=3) # удаление строки с заданным номером
```
или
```python
df = df.dropna() # удаление всех оставшихся NaN
``` -->
5. Сохраните 1 - оставшийся датафрейм и 2 - отдельно его часть только с численными колонками

In [18]:
df = df[(df['km_year'] >= 0) & (df['km_year'] <= 100_000)].copy()
df

,Make,Model,Year,Style,Distance,Engine_capacity(cm3),Fuel_type,Price(euro),km_year,Transmission,km_year_cat
0,Toyota,Prius,2011,Hatchback,195000.0,1800.0,Hybrid,7750.0,17727.272727,Automatic,Medium
1,Renault,Grand Scenic,2014,Universal,135000.0,1500.0,Diesel,8550.0,16875.000000,Manual,Medium
2,Volkswagen,Golf,1998,Hatchback,1.0,1400.0,Petrol,2200.0,0.041667,Manual,Small
3,Renault,Laguna,2012,Universal,110000.0,1500.0,Diesel,6550.0,11000.000000,Manual,Medium
4,Opel,Astra,2006,Universal,200000.0,1600.0,Metan/Propan,4100.0,12500.000000,Manual,Medium
...,...,...,...,...,...,...,...,...,...,...,...
41002,Dacia,Logan Mcv,2015,Universal,89000.0,1500.0,Diesel,7000.0,12714.285714,Manual,Medium
41003,Renault,Modus,2009,Hatchback,225.0,1500.0,Diesel,4500.0,17.307692,Manual,Small
41004,Mercedes,E Class,2016,Sedan,50000.0,1950.0,Diesel,29500.0,8333.333333,Automatic,Small
41005,Mazda,6,2006,Combi,370000.0,2000.0,Diesel,4000.0,23125.000000,Manual,Medium
41006,Renault,Grand Scenic,2006,Minivan,300000.0,1500.0,Diesel,4000.0,18750.000000,Manual,Medium

In [ ]:
def fr_style(df_data, make, model, year):
    sub_df = df_data[(df_data['Make'] == make) & (df_data['Model'] == model) & (df_data['Year'] == year)]

    if sub_df.empty or sub_df['Style'].dropna().empty:
        sub_df = df_data[(df_data['Make'] == make) & (df_data['Model'] == model)]
    if not sub_df['Style'].dropna().empty:
        return sub_df['Style'].mode()[0]
    return None